# Generated by Django 2.1.5 on 2006-12-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='exam_question',
            field=models.ForeignKey(limit_choices_to={'default_question': True}, on_delete=django.db.models.deletion.CASCADE, to='question.ExamQuestion'),
        ),
    ]
