# Generated by Django 2.1.7 on 2019-02-24 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_answer_authenticate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='exam_question',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='answer_choice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='authenticate',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
