# Generated by Django 2.1.7 on 2019-02-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20190224_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
    ]
